### ISSUE TITLE
Nominations Scraper -> congress.gov

### ISSUE THREAD

**Issue by crdunwel** [unitedstates/congress#173]
We need to transition the nominations scraper to congress.gov because thomas.gov is shutting down.

**Comment by JoshData** [comment]
@dwillis points out that there's XML at http://www.senate.gov/general/XML.htm, so we should transition the scraper to use that instead.

**Comment by veselins** [comment]
Is the following exceptions is something related to nominations issue?

[s754-114] Exception:

Traceback (most recent call last):

  File "/LegCyteTools/congress-master/tasks/utils.py", line 173, in process_set
    results = fetch_func(id, options, *extra_args)

  File "/LegCyteTools/congress-master/tasks/bills.py", line 109, in process_bill
    process_amendments(bill_id, xml_as_dict, options)

  File "/LegCyteTools/congress-master/tasks/bills.py", line 216, in process_amendments
    amendment_info.process_amendment(amdt, bill_id, options)

  File "/LegCyteTools/congress-master/tasks/amendment_info.py", line 13, in process_amendment
    amdt = build_amendment_json_dict(amdt_data, options)

  File "/LegCyteTools/congress-master/tasks/amendment_info.py", line 36, in build_amendment_json_dict
    amends_bill = amends_bill_for(amdt_dict.get('amendedBill'))  # almost always present

  File "/LegCyteTools/congress-master/tasks/amendment_info.py", line 146, in amends_bill_for
    bill_id = build_bill_id(amends_bill['type'].lower(), amends_bill['number'], amends_bill['congress'])

TypeError: 'NoneType' object has no attribute '__getitem__'


[s2943-114] Exception:

Traceback (most recent call last):

  File "/LegCyteTools/congress-master/tasks/utils.py", line 173, in process_set
    results = fetch_func(id, options, *extra_args)

  File "/LegCyteTools/congress-master/tasks/bills.py", line 109, in process_bill
    process_amendments(bill_id, xml_as_dict, options)

  File "/LegCyteTools/congress-master/tasks/bills.py", line 216, in process_amendments
    amendment_info.process_amendment(amdt, bill_id, options)

  File "/LegCyteTools/congress-master/tasks/amendment_info.py", line 13, in process_amendment
    amdt = build_amendment_json_dict(amdt_data, options)

  File "/LegCyteTools/congress-master/tasks/amendment_info.py", line 72, in build_amendment_json_dict
    amdt['proposed_at'] = amdt_dict['proposedDate']

KeyError: 'proposedDate'

**Comment by kevinschaul** [comment]
Hi all, I'm may take a stab at this. A few thoughts before I dive in:

The [XML referenced above](https://www.senate.gov/general/XML.htm) seems to show only nominations for the current term. Is there a preferred strategy for handling nominations that predate whatever the current term is?

Unfortunately I don't see a great source data format for nominations. Even [those XML files](https://www.senate.gov/legislative/LIS/nominations/NomCivilianConfirmed.xml) would require parsing names of nominees (or getting that information from another source based on the nomination number PNXXX).

I'm considering having the nominations scraper use Congress.gov's search. [This example query](https://www.congress.gov/search?q={%22source%22:%22nominations%22,%22congress%22:[%22115%22]}&pageSort=actionDesc) could work for finding the nominations with the most recent changes, and the details cold be drawn from the [nomination action pages](https://www.congress.gov/nomination/115th-congress/54?r=1). Does that strategy make sense?

Any other comments before I begin?

**Comment by dwillis** [comment]
@kevinschaul I think it's worth having the XML parser mainly because in theory it would be less brittle than scraping Congress.gov, but I'm not going to die on that hill if others don't feel strongly about it. In either case I think we'd need to do a little bit of parsing to grab the nominee name.

**Comment by JoshData** [comment]
It would be nice to have the full action history (only on Congress.gov?), but either data source is fine with me.

**Comment by dwillis** [comment]
Yeah, I think the full action history is better on Congress.gov. So let's go with a convention scraper of that.

**Comment by AlJohri** [comment]
hi @dwillis @JoshData, I'd be interested in tackling a congress.gov scraper if its still needed. is the task to grab the full action history for each bill?

**Comment by dwillis** [comment]
Hey @AlJohri, thanks! That would be great. We'd want each nominations and all actions for it. There are a couple of wrinkles here: some nominations (especially military ones) represent multiple nominees, while most civilian nominations are for a single person. Others are divided into multiple records for the same `PN` number.

**Comment by AlJohri** [comment]
sounds good! I made some initial progress for parsing a single nomination. This is what the output looks like: https://gist.github.com/AlJohri/80b5c4a55ddfc04eb2a24a413a0b79cd#file-sample-json

I'll look into a couple of those edge cases you mentioned next

**Comment by dwillis** [comment]
This looks good so far, thanks!

**Comment by lwaltman** [comment]
Has any progress been made on this scraper?  Where is the current version?  I just am looking for a somewhat usable one to use to test.

**Comment by AlJohri** [comment]
no sory @lwaltman, but it should be pretty easy to modify https://gist.github.com/AlJohri/80b5c4a55ddfc04eb2a24a413a0b79cd#file-nominations-py

**Comment by Darokrithia** [comment]
Any updates in 2020?  I may be willing to work on this, especially if there already is some infrastructure in place

**Comment by Darokrithia** [comment]
Also, I am more interested in bill data from 1970-2012, which was a part of the thomas scraper

**Comment by dwillis** [comment]
@Darokrithia We've got from 1973-on here: https://www.propublica.org/datastore/dataset/congressional-data-bulk-legislation-bills

**Comment by Darokrithia** [comment]
Perfect!  Thank you!  You may want to update your documentation.  I may be miss reading it, but the documentation for bills implies this data is missing / there is no scrapper.  Thank you once again!

**Comment by dwillis** [comment]
@Darokrithia the documentation is correct in that this project only handles legislation from 2013-onward.

**Comment by ryparker** [comment]
Any movement on this?

**Comment by tmountjr** [comment]
In case anyone else comes looking for this like I did...nominations that were decided by a roll call vote (which...all of them? maybe? I'm not sure) will be listed as part of the `votes` subset. So for instance, the most recent (as of today) nomination for the 119th congress: https://www.senate.gov/legislative/LIS/roll_call_votes/vote1191/vote_119_1_00053.htm

That's senate roll call vote no. 53, and if you run `usc-run votes --congress=119` you'll eventually get `data/119/votes/2025/s53` with a category of `nomination`, including all the up and down votes.
