### ISSUE TITLE
Congress.gov Bills Scrapers Broken

### ISSUE THREAD

**Issue by swt83** [unitedstates/congress#176]
The python script for downloading bills data appears to be broken.  It looks like the URL being pulled is messed up:

```
python run bills --congress=114 --force 
Error downloading http://thomas.loc.gov/cgi-bin/bdquery/d?d114:0:./list/bss/d114HE.lst:[[o]]:

Traceback (most recent call last):

  File "MYPATH/machine/storage/legislation/tasks/utils.py", line 337, in download
    response = scraper.urlopen(url, **urlopen_kwargs)

  File "/usr/local/lib/python2.7/site-packages/scrapelib/__init__.py", line 317, in urlopen
    resp = self.request(method, url, data=body, retry_on_404=retry_on_404, **kwargs)

  File "/usr/local/lib/python2.7/site-packages/scrapelib/__init__.py", line 296, in request
    raise HTTPError(resp)

HTTPError: 404 while retrieving https://www.congress.gov//cgi-bin/bdquery/d?d114:0:./list/bss/d114HE.lst:%5b%5bo%5d%5d

Couldn't download page with offset 0, aborting
Error figuring out which bills to download, aborting.
```

**Comment by JoshData** [comment]
See #175! THOMAS is gone now. (Tear!) But there is new data instead.
