### ISSUE TITLE
Crawler throws exception with KeyError: 'primarySubject'

### ISSUE THREAD

**Issue by veselins** [unitedstates/congress#180]
Hi, 

since last few weeks the when we start the crawler with following command line:
`./run fdsys --collections=BILLSTATUS`
The crawler throws exception for many bills

```
Errors for 240 items:
[hr3195-113] Exception:
Traceback (most recent call last):
  File "/LegCyteTools/congress-master/tasks/utils.py", line 173, in process_set
    results = fetch_func(id, options, *extra_args)
  File "/LegCyteTools/congress-master/tasks/bills.py", line 97, in process_bill
    bill_data = form_bill_json_dict(xml_as_dict)
  File "/LegCyteTools/congress-master/tasks/bills.py", line 174, in form_bill_json_dict
    'subjects_top_term': _fixup_top_term_case(bill_dict['primarySubject']['name']) if bill_dict['primarySubject'] else None,
KeyError: 'primarySubject'
```

And primary result of all of this is:

```
Errors for 240.
Skipped 0.
Saved data for 0.

```

Please, advice.
Best
Veselin

**Comment by JoshData** [comment]
I just pushed a fix in dc4087688f10aa388cbe22c1d8ff4c5ebf842048.

See https://github.com/usgpo/bill-status/issues/25. This was an upstream schema change that no one was told about until after it happened.

**Comment by veselins** [comment]
Seems the issue appear again. But this time after we execute the step 2 of scrapp proces. 
After executing:
`./run bills`

```
./run bills
Updating the congress-legislators repo...

Errors for 137 items:


[hr3195-113] Exception:

Traceback (most recent call last):

  File "/LegCyteTools/congress-master/tasks/utils.py", line 173, in process_set
    results = fetch_func(id, options, *extra_args)

  File "/LegCyteTools/congress-master/tasks/bills.py", line 97, in process_bill
    bill_data = form_bill_json_dict(xml_as_dict)

  File "/LegCyteTools/congress-master/tasks/bills.py", line 174, in form_bill_json_dict
    'subjects_top_term': _fixup_top_term_case(bill_dict['primarySubject']['name']) if bill_dict['primarySubject'] else None,

KeyError: 'primarySubject'
```

**Comment by pqnelson** [comment]
It appears ultimately the GPO is not backporting the bills from prior congresses to use `policyArea` --- e.g., hconres1-113 still has a `primarySubject` tag.

**Comment by JoshData** [comment]
Good catch.

**Comment by JoshData** [comment]
This is good to close, right?

**Comment by dwillis** [comment]
Yes, it is.
