### ISSUE TITLE
Error in Votes Scraper

### ISSUE THREAD

**Issue by swt83** [unitedstates/congress#182]
```
python run votes --congress=114 --session=2016 --force --fast
Going to fetch 16 votes from congress #114 session 2016
[h44-114.2016] Skipping: vote was vacated

Errors for 1 items:


[s149-114.2016] Exception:

Traceback (most recent call last):

  File "MYPATH\tasks\utils.py", lin
e 173, in process_set
    results = fetch_func(id, options, *extra_args)

  File "MYPATH\tasks\vote_info.py",
 line 44, in fetch_vote
    dom = etree.fromstring(body)

  File "lxml.etree.pyx", line 3103, in lxml.etree.fromstring (src\lxml\lxml.etre
e.c:70569)

  File "parser.pxi", line 1828, in lxml.etree._parseMemoryDocument (src\lxml\lxm
l.etree.c:106403)

  File "parser.pxi", line 1716, in lxml.etree._parseDoc (src\lxml\lxml.etree.c:1
05194)

  File "parser.pxi", line 1086, in lxml.etree._BaseParser._parseDoc (src\lxml\lx
ml.etree.c:99876)

  File "parser.pxi", line 580, in lxml.etree._ParserContext._handleParseResultDo
c (src\lxml\lxml.etree.c:94350)

  File "parser.pxi", line 690, in lxml.etree._handleParseResult (src\lxml\lxml.e
tree.c:95786)

  File "parser.pxi", line 620, in lxml.etree._raiseParseError (src\lxml\lxml.etr
ee.c:94853)

XMLSyntaxError: Opening and ending tag mismatch: link line 24 and head, line 26,
 column 12


Errors for 1.
Skipped 1.
Saved data for 14.
```

**Comment by JoshData** [comment]
Sometimes Congress publishes invalid data.
