### ISSUE TITLE
Senate Congress Votes Issue 114th congress

### ISSUE THREAD

**Issue by briggsotis** [unitedstates/congress#198]
Has anyone been able to successfully pull from the senate congress votes? The house votes for the 114th are scraped just fine, but I get a 403 error when trying to pull the xml for the senate. 

Here's what I'm seeing: 

otis@DESKTOP-1KU67Q6:/mnt/c/Users/Phil/Desktop/congress/congress-master$ ./run votes --govtrack --congress=114 --session=2016 --chamber=senate
Error downloading http://www.senate.gov/legislative/LIS/roll_call_lists/vote_menu_114_2.xml:

Traceback (most recent call last):

  File "/mnt/c/Users/Phil/Desktop/congress/congress-master/tasks/utils.py", line 315, in download
    response = scraper.urlopen(url, **urlopen_kwargs)

  File "/usr/local/lib/python2.7/dist-packages/scrapelib/__init__.py", line 317, in urlopen
    resp = self.request(method, url, data=body, retry_on_404=retry_on_404, **kwargs)

  File "/usr/local/lib/python2.7/dist-packages/scrapelib/__init__.py", line 296, in request
    raise HTTPError(resp)

HTTPError: 403 while retrieving http://www.senate.gov/legislative/LIS/roll_call_lists/vote_menu_114_2.xml

Couldn't download Senate vote XML index http://www.senate.gov/legislative/LIS/roll_call_lists/vote_menu_114_2.xml, skipping
Error figuring out which votes to download, aborting.

**Comment by briggsotis** [comment]
Apparently my IP got blocked from the http://www.senate.gov/legislative/LIS/roll_call_lists/vote_menu_114_2.xml web page, but not the others. I changed networks/IPs and was able to retrieve the data fine.

Very strange.
