### ISSUE TITLE
"./run bills --bill_id=s968-112" gives "TypeError: must be string or read-only buffer, not None"

### ISSUE THREAD

**Issue by willcoughlin** [unitedstates/congress#227]
### Details
Running the [sample bills task](https://github.com/unitedstates/congress/wiki/bills#contemporary-bills-2013-present) after fetching XML data from FDSys causes an error to be thrown: "TypeError: must be string or read-only buffer, not None".

- Python version: 2.7.9
- Distro: Raspbian Jessie
- Kernel version: 4.9.35-v7+

### Steps to reproduce
1. Clone the repository on local machine.
2. Create and switch into virtualenv.
3. Install pip dependencies.
4. Run the following tasks:
```
./run fdsys --collections=BILLSTATUS
./run bills --bill_id=s968-112
```

### Detailed output
```
$ ./run bills --bill_id=s968-112

Errors for 1 items:


[s968-112] Exception:

Traceback (most recent call last):

  File "/home/pi/congress/tasks/utils.py", line 173, in process_set
    results = fetch_func(id, options, *extra_args)

  File "/home/pi/congress/tasks/bills.py", line 101, in process_bill
    xml_as_dict = read_fdsys_bulk_bill_status_file(fdsys_xml_path, bill_id)

  File "/home/pi/congress/tasks/bills.py", line 132, in read_fdsys_bulk_bill_status_file
    return xmltodict.parse(fdsys_billstatus, force_list=('item', 'amendment', 'committeeReport', 'link'))

  File "/home/pi/.virtualenvs/congress/local/lib/python2.7/site-packages/xmltodict.py", line 330, in parse
    parser.Parse(xml_input, True)

TypeError: must be string or read-only buffer, not None


Errors for 1.
Skipped 0.
Saved data for 0.
```

**Comment by JoshData** [comment]
The example bill we have in the documentation s968-112 isn't actually valid (it was once). The GPO BILLSTATUS XML bulk data begins with the 113th Congress so that bill precedes the time when the data is available. If you pick any bill starting with the 113th Congress it should work. You could try hr1625-115, which was the recent omnibus bill.
