### ISSUE TITLE
IndexError: string index out of range

### ISSUE THREAD

**Issue by jacobCRP** [unitedstates/congress#237]
Hey ya'll. 

I had this script running great today until my server ran out of space. Upon restarting the script on a drive with more space I received this error:

**./run govinfo --bulkdata=BILLSTATUS**
```

(venv) ubuntu@ip-10-33-1-25:~/congress3/congress$ ./run govinfo --bulkdata=BILLSTATUS
Traceback (most recent call last):

  File "./run", line 71, in <module>
    task_mod.run(options)

  File "/home/ubuntu/congress3/congress/tasks/govinfo.py", line 74, in run
    update_sitemap(BULKDATA_SITEMAPINDEX_PATTERN.format(collection=collection), None, [], options)

  File "/home/ubuntu/congress3/congress/tasks/govinfo.py", line 99, in update_sitemap
    lastmod_cache = rtyaml.load(f)

  File "/home/ubuntu/congress3/congress/venv/local/lib/python2.7/site-packages/rtyaml/__init__.py", line 101, in load
    return do_load(stream, yaml.load)

  File "/home/ubuntu/congress3/congress/venv/local/lib/python2.7/site-packages/rtyaml/__init__.py", line 122, in do_load
    if line[0] != "#":

IndexError: string index out of range
```

Any thoughts?

**Comment by JoshData** [comment]
It looks like it's failing loading a cache file tracking the last modified date of a sitemap. If you clear your cache/govinfo directory it might help (though it may have to re-download a lot next time, depending on what you're using it for).

**Comment by jacobCRP** [comment]
That worked! Thank you.
